name: "build 1st workshop"

on:
  push:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: check out
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
      - name: echo server.js
        run: node server.js
