name: "build 1st workshop"

on:
  push:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: check out and install dependencies
        uses: actions/checkout@v4
      - name: echo server.js
        run: node server.js
